### PR TITLE
New Customization Feature: Min-Width of sections

### PR DESCRIPTION
**Pull request by MephistoJB**
added the possibility to define the min width of a section with the variabel token-size-section-min-width

### CODE REVIEW

**Comment by TilmanGriesel** [comment]
Thank you for your contribution, @MephistoJB! I've reviewed your additions, and they look solid and useful. Everything checks out on my end (LGTM) 👍

**Comment by TilmanGriesel** [comment]
@MephistoJB Just a quick note: it seems that you've updated all the theme files manually. In Graphite, the approach is to edit the files in the `src` directory, specifically the template and tokens. Once you've made your changes, you can run `python3 ./tools/theme_assembler.py` to regenerate and assemble the theme files. 

This process ensures consistency across the theme and makes future edits significantly faster and more efficient. Let me know if you have any questions about this workflow!

**Review by TilmanGriesel — APPROVED** [review]
LGTM (required theme regen and template update)

**Comment by MephistoJB** [comment]
Thanks for the tip. Next Time :)

**Pull request merged**
